language: java
jdk:
  - openjdk8

before_install:
  - chmod +x mvnw

script:
  #./mvnw clean install
  - mvn clean package -Production heroku:deploy

notifications:
  email: stu1901727008@uni-plovdiv.bg